create table cars (
	id INT,
	model VARCHAR(50),
	maker VARCHAR(50),
	year VARCHAR(4)
);
insert into cars (id, model, maker, year) values (1, '911', 'Porsche', 1988);
insert into cars (id, model, maker, year) values (2, 'Capri', 'Mercury', 1993);
insert into cars (id, model, maker, year) values (3, 'Suburban 2500', 'Chevrolet', 2002);
insert into cars (id, model, maker, year) values (4, 'Voyager', 'Plymouth', 1996);
insert into cars (id, model, maker, year) values (5, 'CL-Class', 'Mercedes-Benz', 2012);
insert into cars (id, model, maker, year) values (6, 'Continental', 'Lincoln', 1996);
insert into cars (id, model, maker, year) values (7, 'Bonneville', 'Pontiac', 1995);
insert into cars (id, model, maker, year) values (8, 'MKZ', 'Lincoln', 2011);
insert into cars (id, model, maker, year) values (9, 'RX-7', 'Mazda', 1995);
insert into cars (id, model, maker, year) values (10, 'Genesis Coupe', 'Hyundai', 2011);
insert into cars (id, model, maker, year) values (11, 'Ghost', 'Rolls-Royce', 2010);
insert into cars (id, model, maker, year) values (12, 'Grand Vitara', 'Suzuki', 2004);
insert into cars (id, model, maker, year) values (13, 'Discovery Series II', 'Land Rover', 2001);
insert into cars (id, model, maker, year) values (14, 'Trans Sport', 'Pontiac', 1991);
insert into cars (id, model, maker, year) values (15, 'Type 2', 'Volkswagen', 1985);
insert into cars (id, model, maker, year) values (16, 'E250', 'Ford', 2005);
insert into cars (id, model, maker, year) values (17, '1500', 'GMC', 1998);
insert into cars (id, model, maker, year) values (18, 'Jimmy', 'GMC', 2001);
insert into cars (id, model, maker, year) values (19, 'Accord', 'Honda', 2006);
insert into cars (id, model, maker, year) values (20, 'Cruze', 'Chevrolet', 2012);
insert into cars (id, model, maker, year) values (21, 'Viper', 'Dodge', 2006);
insert into cars (id, model, maker, year) values (22, 'Sunfire', 'Pontiac', 1999);
insert into cars (id, model, maker, year) values (23, 'B-Series', 'Mazda', 2007);
insert into cars (id, model, maker, year) values (24, '626', 'Mazda', 1984);
insert into cars (id, model, maker, year) values (25, 'Villager', 'Mercury', 1998);
insert into cars (id, model, maker, year) values (26, 'Lancer', 'Mitsubishi', 2003);
insert into cars (id, model, maker, year) values (27, 'ES', 'Lexus', 1991);
insert into cars (id, model, maker, year) values (28, 'C-Class', 'Mercedes-Benz', 2004);
insert into cars (id, model, maker, year) values (29, 'Passat', 'Volkswagen', 2002);
insert into cars (id, model, maker, year) values (30, 'Riviera', 'Buick', 1992);
insert into cars (id, model, maker, year) values (31, 'MKX', 'Lincoln', 2008);
insert into cars (id, model, maker, year) values (32, 'SJ', 'Suzuki', 1991);
insert into cars (id, model, maker, year) values (33, 'Charger', 'Dodge', 2009);
insert into cars (id, model, maker, year) values (34, 'M3', 'BMW', 2009);
insert into cars (id, model, maker, year) values (35, 'R-Class', 'Mercedes-Benz', 2009);
insert into cars (id, model, maker, year) values (36, 'SLR McLaren', 'Mercedes-Benz', 2009);
insert into cars (id, model, maker, year) values (37, 'Esprit', 'Lotus', 2004);
insert into cars (id, model, maker, year) values (38, 'Camaro', 'Chevrolet', 1998);
insert into cars (id, model, maker, year) values (39, 'Avalon', 'Toyota', 2006);
insert into cars (id, model, maker, year) values (40, 'C8 Double 12 S', 'Spyker', 2006);
insert into cars (id, model, maker, year) values (41, 'Escape', 'Ford', 2003);
insert into cars (id, model, maker, year) values (42, 'V8', 'Audi', 1994);
insert into cars (id, model, maker, year) values (43, 'Yukon XL 2500', 'GMC', 2000);
insert into cars (id, model, maker, year) values (44, 'LS', 'Lexus', 1994);
insert into cars (id, model, maker, year) values (45, 'Echo', 'Toyota', 2001);
insert into cars (id, model, maker, year) values (46, 'X-90', 'Suzuki', 1997);
insert into cars (id, model, maker, year) values (47, 'Mustang', 'Ford', 2004);
insert into cars (id, model, maker, year) values (48, 'Yukon XL 1500', 'GMC', 2004);
insert into cars (id, model, maker, year) values (49, 'Ram', 'Dodge', 2010);
insert into cars (id, model, maker, year) values (50, 'Yukon XL 2500', 'GMC', 2004);
insert into cars (id, model, maker, year) values (51, 'ES', 'Lexus', 1995);
insert into cars (id, model, maker, year) values (52, 'PT Cruiser', 'Chrysler', 2003);
insert into cars (id, model, maker, year) values (53, 'G', 'Infiniti', 2007);
insert into cars (id, model, maker, year) values (54, 'Eclipse', 'Mitsubishi', 2000);
insert into cars (id, model, maker, year) values (55, 'Cabriolet', 'Volkswagen', 1986);
insert into cars (id, model, maker, year) values (56, '9-3', 'Saab', 2001);
insert into cars (id, model, maker, year) values (57, 'Focus', 'Ford', 2005);
insert into cars (id, model, maker, year) values (58, '9-5', 'Saab', 2009);
insert into cars (id, model, maker, year) values (59, 'CR-X', 'Honda', 1988);
insert into cars (id, model, maker, year) values (60, 'Regal', 'Buick', 2011);
insert into cars (id, model, maker, year) values (61, 'XJ', 'Jaguar', 2006);
insert into cars (id, model, maker, year) values (62, 'SC', 'Lexus', 2008);
insert into cars (id, model, maker, year) values (63, 'S-Class', 'Mercedes-Benz', 1986);
insert into cars (id, model, maker, year) values (64, 'XC70', 'Volvo', 2003);
insert into cars (id, model, maker, year) values (65, '4000s Quattro', 'Audi', 1986);
insert into cars (id, model, maker, year) values (66, 'Amigo', 'Isuzu', 1994);
insert into cars (id, model, maker, year) values (67, 'LR3', 'Land Rover', 2006);
insert into cars (id, model, maker, year) values (68, 'Tacoma', 'Toyota', 2009);
insert into cars (id, model, maker, year) values (69, 'Q', 'Infiniti', 1992);
insert into cars (id, model, maker, year) values (70, 'Elan', 'Lotus', 1991);
insert into cars (id, model, maker, year) values (71, 'Quest', 'Nissan', 2005);
insert into cars (id, model, maker, year) values (72, 'TSX', 'Acura', 2004);
insert into cars (id, model, maker, year) values (73, '745', 'BMW', 2002);
insert into cars (id, model, maker, year) values (74, 'RL', 'Acura', 2008);
insert into cars (id, model, maker, year) values (75, 'Corvette', 'Chevrolet', 2001);
insert into cars (id, model, maker, year) values (76, 'Ciera', 'Oldsmobile', 1992);
insert into cars (id, model, maker, year) values (77, 'Outlander', 'Mitsubishi', 2011);
insert into cars (id, model, maker, year) values (78, 'Corvette', 'Chevrolet', 2003);
insert into cars (id, model, maker, year) values (79, '9-3', 'Saab', 2001);
insert into cars (id, model, maker, year) values (80, 'Rondo', 'Kia', 2007);
insert into cars (id, model, maker, year) values (81, 'LTD', 'Ford', 1986);
insert into cars (id, model, maker, year) values (82, '3 Series', 'BMW', 2008);
insert into cars (id, model, maker, year) values (83, 'GL-Class', 'Mercedes-Benz', 2008);
insert into cars (id, model, maker, year) values (84, 'Carrera GT', 'Porsche', 2005);
insert into cars (id, model, maker, year) values (85, 'Vantage', 'Aston Martin', 2010);
insert into cars (id, model, maker, year) values (86, 'Z4', 'BMW', 2010);
insert into cars (id, model, maker, year) values (87, 'W201', 'Mercedes-Benz', 1991);
insert into cars (id, model, maker, year) values (88, 'Focus', 'Ford', 2002);
insert into cars (id, model, maker, year) values (89, 'QX', 'Infiniti', 2002);
insert into cars (id, model, maker, year) values (90, 'S4', 'Audi', 1993);
insert into cars (id, model, maker, year) values (91, 'Caprice Classic', 'Chevrolet', 1994);
insert into cars (id, model, maker, year) values (92, '9-5', 'Saab', 2001);
insert into cars (id, model, maker, year) values (93, 'XLR-V', 'Cadillac', 2009);
insert into cars (id, model, maker, year) values (94, 'Altima', 'Nissan', 2006);
insert into cars (id, model, maker, year) values (95, 'V40', 'Volvo', 2000);
insert into cars (id, model, maker, year) values (96, 'LTD Crown Victoria', 'Ford', 1987);
insert into cars (id, model, maker, year) values (97, 'Expedition', 'Ford', 2011);
insert into cars (id, model, maker, year) values (98, 'Silverado', 'Chevrolet', 2010);
insert into cars (id, model, maker, year) values (99, 'Metro', 'Geo', 1992);
insert into cars (id, model, maker, year) values (100, 'Legacy', 'Subaru', 1994);
insert into cars (id, model, maker, year) values (101, 'Sentra', 'Nissan', 2001);
insert into cars (id, model, maker, year) values (102, 'Mazda2', 'Mazda', 2011);
insert into cars (id, model, maker, year) values (103, 'Altima', 'Nissan', 2001);
insert into cars (id, model, maker, year) values (104, 'G37', 'Infiniti', 2011);
insert into cars (id, model, maker, year) values (105, '525', 'BMW', 2005);
insert into cars (id, model, maker, year) values (106, 'LeMans', 'Pontiac', 1966);
insert into cars (id, model, maker, year) values (107, 'Elantra', 'Hyundai', 1992);
insert into cars (id, model, maker, year) values (108, 'DBS', 'Aston Martin', 2009);
insert into cars (id, model, maker, year) values (109, 'GS', 'Lexus', 2011);
insert into cars (id, model, maker, year) values (110, 'Grand Caravan', 'Dodge', 1998);
insert into cars (id, model, maker, year) values (111, 'NSX', 'Acura', 2000);
insert into cars (id, model, maker, year) values (112, 'Lynx', 'Mercury', 1985);
insert into cars (id, model, maker, year) values (113, 'Explorer', 'Ford', 2008);
insert into cars (id, model, maker, year) values (114, 'Grand Prix', 'Pontiac', 1967);
insert into cars (id, model, maker, year) values (115, 'Golf', 'Volkswagen', 1976);
insert into cars (id, model, maker, year) values (116, 'Bonneville', 'Pontiac', 1991);
insert into cars (id, model, maker, year) values (117, '5 Series', 'BMW', 1992);
insert into cars (id, model, maker, year) values (118, 'Laser', 'Plymouth', 1989);
insert into cars (id, model, maker, year) values (119, 'Express', 'Chevrolet', 2006);
insert into cars (id, model, maker, year) values (120, 'Silverado 2500', 'Chevrolet', 2003);
insert into cars (id, model, maker, year) values (121, 'Spider', 'Alfa Romeo', 1992);
insert into cars (id, model, maker, year) values (122, 'Sportage', 'Kia', 1998);
insert into cars (id, model, maker, year) values (123, 'Daewoo Lacetti', 'Suzuki', 2008);
insert into cars (id, model, maker, year) values (124, 'S80', 'Volvo', 2010);
insert into cars (id, model, maker, year) values (125, 'C70', 'Volvo', 2012);
insert into cars (id, model, maker, year) values (126, 'F-Series', 'Ford', 1989);
insert into cars (id, model, maker, year) values (127, 'Prius', 'Toyota', 2003);
insert into cars (id, model, maker, year) values (128, 'Grand Marquis', 'Mercury', 1987);
insert into cars (id, model, maker, year) values (129, 'Jetta', 'Volkswagen', 1985);
insert into cars (id, model, maker, year) values (130, 'Dakota', 'Dodge', 2000);
insert into cars (id, model, maker, year) values (131, 'Acadia', 'GMC', 2007);
insert into cars (id, model, maker, year) values (132, 'Sierra 2500', 'GMC', 2001);
insert into cars (id, model, maker, year) values (133, 'RAV4', 'Toyota', 2007);
insert into cars (id, model, maker, year) values (134, 'Tundra', 'Toyota', 2012);
insert into cars (id, model, maker, year) values (135, 'Express 2500', 'Chevrolet', 1998);
insert into cars (id, model, maker, year) values (136, 'Optima', 'Kia', 2011);
insert into cars (id, model, maker, year) values (137, 'Pajero', 'Mitsubishi', 2003);
insert into cars (id, model, maker, year) values (138, 'Azera', 'Hyundai', 2009);
insert into cars (id, model, maker, year) values (139, 'XC70', 'Volvo', 2007);
insert into cars (id, model, maker, year) values (140, 'XC90', 'Volvo', 2008);
insert into cars (id, model, maker, year) values (141, 'Quattro', 'Audi', 1992);
insert into cars (id, model, maker, year) values (142, 'Touareg 2', 'Volkswagen', 2008);
insert into cars (id, model, maker, year) values (143, 'Fleetwood', 'Cadillac', 1995);
insert into cars (id, model, maker, year) values (144, 'TL', 'Acura', 2000);
insert into cars (id, model, maker, year) values (145, 'Durango', 'Dodge', 2011);
insert into cars (id, model, maker, year) values (146, 'DBS', 'Aston Martin', 2009);
insert into cars (id, model, maker, year) values (147, 'SL-Class', 'Mercedes-Benz', 2009);
insert into cars (id, model, maker, year) values (148, 'Laser', 'Ford', 1989);
insert into cars (id, model, maker, year) values (149, '62', 'Maybach', 2009);
insert into cars (id, model, maker, year) values (150, 'Tacoma Xtra', 'Toyota', 2000);
insert into cars (id, model, maker, year) values (151, 'RX', 'Lexus', 2008);
insert into cars (id, model, maker, year) values (152, 'R-Class', 'Mercedes-Benz', 2011);
insert into cars (id, model, maker, year) values (153, 'Yukon', 'GMC', 2012);
insert into cars (id, model, maker, year) values (154, 'E-Class', 'Mercedes-Benz', 2001);
insert into cars (id, model, maker, year) values (155, 'S10', 'Chevrolet', 2001);
insert into cars (id, model, maker, year) values (156, 'Continental', 'Lincoln', 1989);
insert into cars (id, model, maker, year) values (157, '626', 'Mazda', 2001);
insert into cars (id, model, maker, year) values (158, 'Astro', 'Chevrolet', 2004);
insert into cars (id, model, maker, year) values (159, 'Sephia', 'Kia', 2000);
insert into cars (id, model, maker, year) values (160, 'DBS', 'Aston Martin', 2012);
insert into cars (id, model, maker, year) values (161, 'Yukon XL 2500', 'GMC', 2001);
insert into cars (id, model, maker, year) values (162, 'RX-7', 'Mazda', 1990);
insert into cars (id, model, maker, year) values (163, 'XC70', 'Volvo', 2009);
insert into cars (id, model, maker, year) values (164, 'Riviera', 'Buick', 1997);
insert into cars (id, model, maker, year) values (165, 'XF', 'Jaguar', 2009);
insert into cars (id, model, maker, year) values (166, 'S4', 'Audi', 2005);
insert into cars (id, model, maker, year) values (167, 'Sentra', 'Nissan', 1994);
insert into cars (id, model, maker, year) values (168, '7 Series', 'BMW', 2002);
insert into cars (id, model, maker, year) values (169, 'RX-7', 'Mazda', 1995);
insert into cars (id, model, maker, year) values (170, 'Elan', 'Lotus', 1994);
insert into cars (id, model, maker, year) values (171, 'Ram Van 2500', 'Dodge', 2002);
insert into cars (id, model, maker, year) values (172, 'Equus', 'Hyundai', 2011);
insert into cars (id, model, maker, year) values (173, 'G3', 'Pontiac', 2009);
insert into cars (id, model, maker, year) values (174, 'Matrix', 'Toyota', 2007);
insert into cars (id, model, maker, year) values (175, 'S2000', 'Honda', 2007);
insert into cars (id, model, maker, year) values (176, 'GTI', 'Volkswagen', 1985);
insert into cars (id, model, maker, year) values (177, 'Grand Voyager', 'Plymouth', 1995);
insert into cars (id, model, maker, year) values (178, '3500 Club Coupe', 'GMC', 1993);
insert into cars (id, model, maker, year) values (179, 'Suburban 2500', 'Chevrolet', 2004);
insert into cars (id, model, maker, year) values (180, 'Ram 50', 'Dodge', 1993);
insert into cars (id, model, maker, year) values (181, 'Tempest', 'Pontiac', 1961);
insert into cars (id, model, maker, year) values (182, 'E250', 'Ford', 2008);
insert into cars (id, model, maker, year) values (183, '4Runner', 'Toyota', 2002);
insert into cars (id, model, maker, year) values (184, 'LS', 'Lexus', 1993);
insert into cars (id, model, maker, year) values (185, 'Space', 'Isuzu', 1993);
insert into cars (id, model, maker, year) values (186, 'RX', 'Lexus', 2000);
insert into cars (id, model, maker, year) values (187, 'Tacoma', 'Toyota', 1996);
insert into cars (id, model, maker, year) values (188, 'E-Series', 'Ford', 1991);
insert into cars (id, model, maker, year) values (189, 'Continental Mark VII', 'Lincoln', 1986);
insert into cars (id, model, maker, year) values (190, 'A4', 'Audi', 2012);
insert into cars (id, model, maker, year) values (191, 'XLR-V', 'Cadillac', 2007);
insert into cars (id, model, maker, year) values (192, '1500', 'GMC', 1994);
insert into cars (id, model, maker, year) values (193, 'X3', 'BMW', 2012);
insert into cars (id, model, maker, year) values (194, 'Grand Prix', 'Pontiac', 1987);
insert into cars (id, model, maker, year) values (195, 'Quattro', 'Audi', 1985);
insert into cars (id, model, maker, year) values (196, 'Canyon', 'GMC', 2010);
insert into cars (id, model, maker, year) values (197, 'Matrix', 'Toyota', 2010);
insert into cars (id, model, maker, year) values (198, 'GTI', 'Volkswagen', 2006);
insert into cars (id, model, maker, year) values (199, 'Express 2500', 'Chevrolet', 1999);
insert into cars (id, model, maker, year) values (200, '5 Series', 'BMW', 1994);
insert into cars (id, model, maker, year) values (201, 'Malibu', 'Chevrolet', 2003);
insert into cars (id, model, maker, year) values (202, 'G6', 'Pontiac', 2010);
insert into cars (id, model, maker, year) values (203, 'Legacy', 'Subaru', 2000);
insert into cars (id, model, maker, year) values (204, 'H2 SUV', 'Hummer', 2006);
insert into cars (id, model, maker, year) values (205, 'Esperante', 'Panoz', 2007);
insert into cars (id, model, maker, year) values (206, 'Truck', 'Mitsubishi', 1996);
insert into cars (id, model, maker, year) values (207, '626', 'Mazda', 1994);
insert into cars (id, model, maker, year) values (208, 'Fusion', 'Ford', 2006);
insert into cars (id, model, maker, year) values (209, 'G-Class', 'Mercedes-Benz', 2004);
insert into cars (id, model, maker, year) values (210, 'Q', 'Infiniti', 2001);
insert into cars (id, model, maker, year) values (211, 'Fifth Ave', 'Chrysler', 1993);
insert into cars (id, model, maker, year) values (212, 'SM', 'Citroën', 1972);
insert into cars (id, model, maker, year) values (213, 'Freestyle', 'Ford', 2007);
insert into cars (id, model, maker, year) values (214, 'Beretta', 'Chevrolet', 1995);
insert into cars (id, model, maker, year) values (215, '9000', 'Saab', 1992);
insert into cars (id, model, maker, year) values (216, 'Uplander', 'Chevrolet', 2007);
insert into cars (id, model, maker, year) values (217, '458 Italia', 'Ferrari', 2011);
insert into cars (id, model, maker, year) values (218, 'Corvette', 'Chevrolet', 2007);
insert into cars (id, model, maker, year) values (219, 'Legacy', 'Subaru', 1992);
insert into cars (id, model, maker, year) values (220, '9-5', 'Saab', 2007);
insert into cars (id, model, maker, year) values (221, 'RAV4', 'Toyota', 2000);
insert into cars (id, model, maker, year) values (222, 'Prelude', 'Honda', 1992);
insert into cars (id, model, maker, year) values (223, 'Mini', 'Austin', 1959);
insert into cars (id, model, maker, year) values (224, 'Impreza', 'Subaru', 1998);
insert into cars (id, model, maker, year) values (225, 'Concorde', 'Chrysler', 2002);
insert into cars (id, model, maker, year) values (226, 'Magnum', 'Dodge', 2005);
insert into cars (id, model, maker, year) values (227, 'Sierra 1500', 'GMC', 2011);
insert into cars (id, model, maker, year) values (228, 'Pajero', 'Mitsubishi', 1985);
insert into cars (id, model, maker, year) values (229, 'RAV4', 'Toyota', 2001);
insert into cars (id, model, maker, year) values (230, 'Dakota', 'Dodge', 1992);
insert into cars (id, model, maker, year) values (231, 'CT', 'Lexus', 2012);
insert into cars (id, model, maker, year) values (232, 'Clubman', 'MINI', 2009);
insert into cars (id, model, maker, year) values (233, 'Mustang', 'Ford', 2000);
insert into cars (id, model, maker, year) values (234, 'W201', 'Mercedes-Benz', 1984);
insert into cars (id, model, maker, year) values (235, 'DTS', 'Cadillac', 2010);
insert into cars (id, model, maker, year) values (236, 'TT', 'Audi', 2001);
insert into cars (id, model, maker, year) values (237, '4000', 'Audi', 1987);
insert into cars (id, model, maker, year) values (238, 'F350', 'Ford', 2001);
insert into cars (id, model, maker, year) values (239, 'MDX', 'Acura', 2006);
insert into cars (id, model, maker, year) values (240, 'Sunbird', 'Pontiac', 1989);
insert into cars (id, model, maker, year) values (241, 'Savana Cargo Van', 'GMC', 2006);
insert into cars (id, model, maker, year) values (242, 'Yukon Denali', 'GMC', 2000);
insert into cars (id, model, maker, year) values (243, 'S90', 'Volvo', 1998);
insert into cars (id, model, maker, year) values (244, 'Savana 1500', 'GMC', 2001);
insert into cars (id, model, maker, year) values (245, 'Sentra', 'Nissan', 2003);
insert into cars (id, model, maker, year) values (246, '900', 'Saab', 1998);
insert into cars (id, model, maker, year) values (247, 'G', 'Infiniti', 2006);
insert into cars (id, model, maker, year) values (248, 'Suburban 2500', 'GMC', 1995);
insert into cars (id, model, maker, year) values (249, 'S5', 'Audi', 2011);
insert into cars (id, model, maker, year) values (250, 'Sorento', 'Kia', 2007);
insert into cars (id, model, maker, year) values (251, 'Galant', 'Mitsubishi', 2003);
insert into cars (id, model, maker, year) values (252, 'Eldorado', 'Cadillac', 1996);
insert into cars (id, model, maker, year) values (253, 'Esteem', 'Suzuki', 1998);
insert into cars (id, model, maker, year) values (254, 'Murano', 'Nissan', 2010);
insert into cars (id, model, maker, year) values (255, 'Esteem', 'Suzuki', 1998);
insert into cars (id, model, maker, year) values (256, 'Protege', 'Mazda', 2003);
insert into cars (id, model, maker, year) values (257, 'Sequoia', 'Toyota', 2003);
insert into cars (id, model, maker, year) values (258, 'IS', 'Lexus', 2006);
insert into cars (id, model, maker, year) values (259, 'Riviera', 'Buick', 1985);
insert into cars (id, model, maker, year) values (260, 'Golf', 'Volkswagen', 1991);
insert into cars (id, model, maker, year) values (261, '900', 'Saab', 1994);
insert into cars (id, model, maker, year) values (262, 'F250', 'Ford', 2005);
insert into cars (id, model, maker, year) values (263, 'Allroad', 'Audi', 2003);
insert into cars (id, model, maker, year) values (264, 'C-Class', 'Mercedes-Benz', 1994);
insert into cars (id, model, maker, year) values (265, 'Ram 1500', 'Dodge', 2006);
insert into cars (id, model, maker, year) values (266, 'Odyssey', 'Honda', 2000);
insert into cars (id, model, maker, year) values (267, 'Acadia', 'GMC', 2010);
insert into cars (id, model, maker, year) values (268, 'Caravan', 'Dodge', 2012);
insert into cars (id, model, maker, year) values (269, 'LX', 'Lexus', 2000);
insert into cars (id, model, maker, year) values (270, 'Corolla', 'Toyota', 2008);
insert into cars (id, model, maker, year) values (271, 'Discovery', 'Land Rover', 2002);
insert into cars (id, model, maker, year) values (272, 'Bonneville', 'Pontiac', 1990);
insert into cars (id, model, maker, year) values (273, 'CX', 'Citroën', 1974);
insert into cars (id, model, maker, year) values (274, 'Prelude', 'Honda', 1992);
insert into cars (id, model, maker, year) values (275, '3000GT', 'Mitsubishi', 1999);
insert into cars (id, model, maker, year) values (276, 'RDX', 'Acura', 2009);
insert into cars (id, model, maker, year) values (277, 'M3', 'BMW', 2009);
insert into cars (id, model, maker, year) values (278, 'Malibu', 'Chevrolet', 1997);
insert into cars (id, model, maker, year) values (279, 'Escape', 'Ford', 2001);
insert into cars (id, model, maker, year) values (280, 'J', 'Infiniti', 1993);
insert into cars (id, model, maker, year) values (281, 'Forte', 'Kia', 2012);
insert into cars (id, model, maker, year) values (282, 'V40', 'Volvo', 2003);
insert into cars (id, model, maker, year) values (283, 'Scirocco', 'Volkswagen', 1984);
insert into cars (id, model, maker, year) values (284, 'Range Rover', 'Land Rover', 1986);
insert into cars (id, model, maker, year) values (285, 'Verano', 'Buick', 2012);
insert into cars (id, model, maker, year) values (286, 'Econoline E250', 'Ford', 1993);
insert into cars (id, model, maker, year) values (287, 'MPV', 'Mazda', 2000);
insert into cars (id, model, maker, year) values (288, 'Equator', 'Suzuki', 2012);
insert into cars (id, model, maker, year) values (289, 'Crossfire', 'Chrysler', 2008);
insert into cars (id, model, maker, year) values (290, 'Tundra', 'Toyota', 2004);
insert into cars (id, model, maker, year) values (291, 'Envoy', 'GMC', 2007);
insert into cars (id, model, maker, year) values (292, 'Fit', 'Honda', 2008);
insert into cars (id, model, maker, year) values (293, 'CR-V', 'Honda', 2011);
insert into cars (id, model, maker, year) values (294, 'Astro', 'Chevrolet', 1997);
insert into cars (id, model, maker, year) values (295, 'Ram Van 3500', 'Dodge', 1998);
insert into cars (id, model, maker, year) values (296, 'Alero', 'Oldsmobile', 2000);
insert into cars (id, model, maker, year) values (297, 'Wrangler', 'Jeep', 2001);
insert into cars (id, model, maker, year) values (298, 'Impala', 'Chevrolet', 2008);
insert into cars (id, model, maker, year) values (299, '3000GT', 'Mitsubishi', 1992);
insert into cars (id, model, maker, year) values (300, 'Suburban 1500', 'Chevrolet', 2009);
insert into cars (id, model, maker, year) values (301, 'LTD', 'Ford', 1986);
insert into cars (id, model, maker, year) values (302, 'Type 2', 'Volkswagen', 1990);
insert into cars (id, model, maker, year) values (303, 'Fit', 'Honda', 2009);
insert into cars (id, model, maker, year) values (304, '968', 'Porsche', 1993);
insert into cars (id, model, maker, year) values (305, 'Highlander', 'Toyota', 2009);
insert into cars (id, model, maker, year) values (306, 'Caravan', 'Dodge', 1995);
insert into cars (id, model, maker, year) values (307, '9-7X', 'Saab', 2007);
insert into cars (id, model, maker, year) values (308, 'Odyssey', 'Honda', 1998);
insert into cars (id, model, maker, year) values (309, 'Cougar', 'Mercury', 1990);
insert into cars (id, model, maker, year) values (310, 'QX', 'Infiniti', 2001);
insert into cars (id, model, maker, year) values (311, 'G', 'Infiniti', 1992);
insert into cars (id, model, maker, year) values (312, 'MX-3', 'Mazda', 1993);
insert into cars (id, model, maker, year) values (313, 'Beetle', 'Volkswagen', 1967);
insert into cars (id, model, maker, year) values (314, 'Impreza WRX', 'Subaru', 2011);
insert into cars (id, model, maker, year) values (315, 'S40', 'Volvo', 2001);
insert into cars (id, model, maker, year) values (316, 'Aerio', 'Suzuki', 2005);
insert into cars (id, model, maker, year) values (317, 'Cruze', 'Chevrolet', 2011);
insert into cars (id, model, maker, year) values (318, 'RDX', 'Acura', 2012);
insert into cars (id, model, maker, year) values (319, 'Express 1500', 'Chevrolet', 2005);
insert into cars (id, model, maker, year) values (320, 'Sequoia', 'Toyota', 2006);
insert into cars (id, model, maker, year) values (321, 'Express', 'Chevrolet', 2011);
insert into cars (id, model, maker, year) values (322, 'Gallardo', 'Lamborghini', 2007);
insert into cars (id, model, maker, year) values (323, 'Montero Sport', 'Mitsubishi', 2000);
insert into cars (id, model, maker, year) values (324, 'Tracer', 'Mercury', 1989);
insert into cars (id, model, maker, year) values (325, 'Camry Solara', 'Toyota', 2006);
insert into cars (id, model, maker, year) values (326, 'Ram 50', 'Dodge', 1992);
insert into cars (id, model, maker, year) values (327, 'Silverado 2500', 'Chevrolet', 2000);
insert into cars (id, model, maker, year) values (328, 'Chevette', 'Pontiac', 1987);
insert into cars (id, model, maker, year) values (329, 'GTI', 'Volkswagen', 1986);
insert into cars (id, model, maker, year) values (330, 'Mountaineer', 'Mercury', 1997);
insert into cars (id, model, maker, year) values (331, 'Jimmy', 'GMC', 2001);
insert into cars (id, model, maker, year) values (332, 'Grand Cherokee', 'Jeep', 2008);
insert into cars (id, model, maker, year) values (333, 'Gallardo', 'Lamborghini', 2009);
insert into cars (id, model, maker, year) values (334, 'Grand Marquis', 'Mercury', 1990);
insert into cars (id, model, maker, year) values (335, '6000', 'Pontiac', 1988);
insert into cars (id, model, maker, year) values (336, 'Topaz', 'Mercury', 1989);
insert into cars (id, model, maker, year) values (337, 'Mazdaspeed 3', 'Mazda', 2011);
insert into cars (id, model, maker, year) values (338, 'ES', 'Lexus', 1995);
insert into cars (id, model, maker, year) values (339, 'RX-8', 'Mazda', 2006);
insert into cars (id, model, maker, year) values (340, 'Explorer', 'Ford', 1991);
insert into cars (id, model, maker, year) values (341, 'Corvette', 'Chevrolet', 1954);
insert into cars (id, model, maker, year) values (342, 'Phantom', 'Rolls-Royce', 2012);
insert into cars (id, model, maker, year) values (343, 'Jetta', 'Volkswagen', 1991);
insert into cars (id, model, maker, year) values (344, 'Grand Am', 'Pontiac', 2005);
insert into cars (id, model, maker, year) values (345, 'Terrain', 'GMC', 2011);
insert into cars (id, model, maker, year) values (346, 'Prius', 'Toyota', 2011);
insert into cars (id, model, maker, year) values (347, 'Grand Cherokee', 'Jeep', 2000);
insert into cars (id, model, maker, year) values (348, 'Pajero', 'Mitsubishi', 1997);
insert into cars (id, model, maker, year) values (349, 'Country', 'Ford', 1967);
insert into cars (id, model, maker, year) values (350, 'Taurus', 'Ford', 1991);
insert into cars (id, model, maker, year) values (351, 'Fusion', 'Ford', 2006);
insert into cars (id, model, maker, year) values (352, 'Villager', 'Mercury', 1999);
insert into cars (id, model, maker, year) values (353, '57', 'Maybach', 2008);
insert into cars (id, model, maker, year) values (354, 'Samurai', 'Suzuki', 1993);
insert into cars (id, model, maker, year) values (355, 'Flex', 'Ford', 2013);
insert into cars (id, model, maker, year) values (356, 'Cooper', 'MINI', 2011);
insert into cars (id, model, maker, year) values (357, 'Elan', 'Lotus', 1992);
insert into cars (id, model, maker, year) values (358, 'Suburban 2500', 'GMC', 1992);
insert into cars (id, model, maker, year) values (359, 'RL', 'Acura', 2007);
insert into cars (id, model, maker, year) values (360, 'Topaz', 'Mercury', 1993);
insert into cars (id, model, maker, year) values (361, 'GTI', 'Volkswagen', 1986);
insert into cars (id, model, maker, year) values (362, 'Legacy', 'Subaru', 1991);
insert into cars (id, model, maker, year) values (363, 'Sentra', 'Nissan', 2000);
insert into cars (id, model, maker, year) values (364, 'Regal', 'Buick', 1997);
insert into cars (id, model, maker, year) values (365, 'CL-Class', 'Mercedes-Benz', 2005);
insert into cars (id, model, maker, year) values (366, 'Miata MX-5', 'Mazda', 1992);
insert into cars (id, model, maker, year) values (367, 'GX', 'Lexus', 2007);
insert into cars (id, model, maker, year) values (368, 'Sunbird', 'Pontiac', 1992);
insert into cars (id, model, maker, year) values (369, 'Town Car', 'Lincoln', 1997);
insert into cars (id, model, maker, year) values (370, 'Tacoma', 'Toyota', 2010);
insert into cars (id, model, maker, year) values (371, 'SLK-Class', 'Mercedes-Benz', 2001);
insert into cars (id, model, maker, year) values (372, 'Citation', 'Chevrolet', 1980);
insert into cars (id, model, maker, year) values (373, 'S-Series', 'Saturn', 1997);
insert into cars (id, model, maker, year) values (374, 'Pajero', 'Mitsubishi', 1986);
insert into cars (id, model, maker, year) values (375, 'Classic', 'Chevrolet', 2004);
insert into cars (id, model, maker, year) values (376, 'Trans Sport', 'Pontiac', 1994);
insert into cars (id, model, maker, year) values (377, 'Suburban 1500', 'Chevrolet', 2009);
insert into cars (id, model, maker, year) values (378, 'Touareg', 'Volkswagen', 2009);
insert into cars (id, model, maker, year) values (379, 'Express 1500', 'Chevrolet', 1999);
insert into cars (id, model, maker, year) values (380, '2500', 'GMC', 1997);
insert into cars (id, model, maker, year) values (381, 'GX', 'Lexus', 2010);
insert into cars (id, model, maker, year) values (382, 'Ram', 'Dodge', 2007);
insert into cars (id, model, maker, year) values (383, 'Outlander Sport', 'Mitsubishi', 2012);
insert into cars (id, model, maker, year) values (384, 'Suburban 1500', 'Chevrolet', 1992);
insert into cars (id, model, maker, year) values (385, 'TundraMax', 'Toyota', 2012);
insert into cars (id, model, maker, year) values (386, 'S-Class', 'Mercedes-Benz', 2000);
insert into cars (id, model, maker, year) values (387, 'M-Class', 'Mercedes-Benz', 2001);
insert into cars (id, model, maker, year) values (388, 'Galant', 'Mitsubishi', 2003);
insert into cars (id, model, maker, year) values (389, 'GTI', 'Volkswagen', 2006);
insert into cars (id, model, maker, year) values (390, 'Cordia', 'Mitsubishi', 1986);
insert into cars (id, model, maker, year) values (391, 'Diablo', 'Lamborghini', 1991);
insert into cars (id, model, maker, year) values (392, 'Park Avenue', 'Buick', 1994);
insert into cars (id, model, maker, year) values (393, 'Reatta', 'Buick', 1990);
insert into cars (id, model, maker, year) values (394, 'Sierra 2500', 'GMC', 2005);
insert into cars (id, model, maker, year) values (395, 'Galant', 'Mitsubishi', 1992);
insert into cars (id, model, maker, year) values (396, '5 Series', 'BMW', 1995);
insert into cars (id, model, maker, year) values (397, 'Venture', 'Chevrolet', 2002);
insert into cars (id, model, maker, year) values (398, 'Cutlass Supreme', 'Oldsmobile', 1994);
insert into cars (id, model, maker, year) values (399, 'TSX', 'Acura', 2012);
insert into cars (id, model, maker, year) values (400, 'RAV4', 'Toyota', 2005);
insert into cars (id, model, maker, year) values (401, 'Optima', 'Kia', 2001);
insert into cars (id, model, maker, year) values (402, 'VUE', 'Saturn', 2010);
insert into cars (id, model, maker, year) values (403, 'Firebird', 'Pontiac', 1993);
insert into cars (id, model, maker, year) values (404, 'Corvette', 'Chevrolet', 2012);
insert into cars (id, model, maker, year) values (405, 'Pajero', 'Mitsubishi', 1988);
insert into cars (id, model, maker, year) values (406, 'TL', 'Acura', 2004);
insert into cars (id, model, maker, year) values (407, 'IS F', 'Lexus', 2008);
insert into cars (id, model, maker, year) values (408, 'Sportvan G20', 'Chevrolet', 1994);
insert into cars (id, model, maker, year) values (409, 'Camaro', 'Chevrolet', 1992);
insert into cars (id, model, maker, year) values (410, 'Tacoma', 'Toyota', 2011);
insert into cars (id, model, maker, year) values (411, 'Town & Country', 'Chrysler', 2008);
insert into cars (id, model, maker, year) values (412, 'Contour', 'Ford', 1997);
insert into cars (id, model, maker, year) values (413, 'Aerostar', 'Ford', 1996);
insert into cars (id, model, maker, year) values (414, 'Marquis', 'Mercury', 1986);
insert into cars (id, model, maker, year) values (415, 'R-Class', 'Mercedes-Benz', 2009);
insert into cars (id, model, maker, year) values (416, 'Galant', 'Mitsubishi', 1995);
insert into cars (id, model, maker, year) values (417, 'Ram 1500', 'Dodge', 2007);
insert into cars (id, model, maker, year) values (418, 'Cougar', 'Mercury', 1992);
insert into cars (id, model, maker, year) values (419, 'xB', 'Scion', 2005);
insert into cars (id, model, maker, year) values (420, '911', 'Porsche', 2013);
insert into cars (id, model, maker, year) values (421, 'Montero Sport', 'Mitsubishi', 2001);
insert into cars (id, model, maker, year) values (422, 'TT', 'Audi', 2002);
insert into cars (id, model, maker, year) values (423, 'E150', 'Ford', 2010);
insert into cars (id, model, maker, year) values (424, 'Versa', 'Nissan', 2008);
insert into cars (id, model, maker, year) values (425, 'Colorado', 'Chevrolet', 2005);
insert into cars (id, model, maker, year) values (426, 'Defender', 'Land Rover', 1993);
insert into cars (id, model, maker, year) values (427, 'Pajero', 'Mitsubishi', 2003);
insert into cars (id, model, maker, year) values (428, 'Yukon', 'GMC', 1992);
insert into cars (id, model, maker, year) values (429, 'Park Avenue', 'Buick', 1994);
insert into cars (id, model, maker, year) values (430, 'LUV', 'Chevrolet', 1979);
insert into cars (id, model, maker, year) values (431, 'Alero', 'Oldsmobile', 1999);
insert into cars (id, model, maker, year) values (432, 'E150', 'Ford', 2006);
insert into cars (id, model, maker, year) values (433, 'Sprinter 2500', 'Mercedes-Benz', 2012);
insert into cars (id, model, maker, year) values (434, 'Grand Cherokee', 'Jeep', 2005);
insert into cars (id, model, maker, year) values (435, 'Fusion', 'Ford', 2012);
insert into cars (id, model, maker, year) values (436, 'Chariot', 'Mitsubishi', 1992);
insert into cars (id, model, maker, year) values (437, 'Corsica', 'Chevrolet', 1994);
insert into cars (id, model, maker, year) values (438, 'Vigor', 'Acura', 1993);
insert into cars (id, model, maker, year) values (439, 'Sienna', 'Toyota', 2005);
insert into cars (id, model, maker, year) values (440, 'Mustang', 'Ford', 2010);
insert into cars (id, model, maker, year) values (441, '350Z', 'Nissan', 2008);
insert into cars (id, model, maker, year) values (442, 'Legacy', 'Subaru', 1998);
insert into cars (id, model, maker, year) values (443, 'rio', 'Volkswagen', 2001);
insert into cars (id, model, maker, year) values (444, 'Optima', 'Kia', 2012);
insert into cars (id, model, maker, year) values (445, 'Regal', 'Buick', 2003);
insert into cars (id, model, maker, year) values (446, 'Suburban 1500', 'Chevrolet', 1996);
insert into cars (id, model, maker, year) values (447, 'Land Cruiser', 'Toyota', 2001);
insert into cars (id, model, maker, year) values (448, 'Express 2500', 'Chevrolet', 2004);
insert into cars (id, model, maker, year) values (449, 'Sierra 2500', 'GMC', 2012);
insert into cars (id, model, maker, year) values (450, 'CC', 'Volkswagen', 2012);
insert into cars (id, model, maker, year) values (451, 'MKS', 'Lincoln', 2012);
insert into cars (id, model, maker, year) values (452, 'Accord', 'Honda', 2004);
insert into cars (id, model, maker, year) values (453, 'Continental Super', 'Bentley', 2010);
insert into cars (id, model, maker, year) values (454, 'Pilot', 'Honda', 2009);
insert into cars (id, model, maker, year) values (455, 'Mustang', 'Ford', 1986);
insert into cars (id, model, maker, year) values (456, 'Century', 'Buick', 2005);
insert into cars (id, model, maker, year) values (457, 'Viper RT/10', 'Dodge', 1993);
insert into cars (id, model, maker, year) values (458, 'CR-X', 'Honda', 1984);
insert into cars (id, model, maker, year) values (459, 'Explorer Sport Trac', 'Ford', 2000);
insert into cars (id, model, maker, year) values (460, 'Cutlass Supreme', 'Oldsmobile', 1992);
insert into cars (id, model, maker, year) values (461, 'Sephia', 'Kia', 2001);
insert into cars (id, model, maker, year) values (462, 'Maxima', 'Nissan', 1997);
insert into cars (id, model, maker, year) values (463, 'New Beetle', 'Volkswagen', 2009);
insert into cars (id, model, maker, year) values (464, 'Jimmy', 'GMC', 1999);
insert into cars (id, model, maker, year) values (465, 'RL', 'Acura', 1998);
insert into cars (id, model, maker, year) values (466, 'XK Series', 'Jaguar', 1999);
insert into cars (id, model, maker, year) values (467, 'Grand Am', 'Pontiac', 2001);
insert into cars (id, model, maker, year) values (468, 'Chariot', 'Mitsubishi', 1989);
insert into cars (id, model, maker, year) values (469, '400SEL', 'Mercedes-Benz', 1993);
insert into cars (id, model, maker, year) values (470, 'M6', 'BMW', 2008);
insert into cars (id, model, maker, year) values (471, 'SLK-Class', 'Mercedes-Benz', 2004);
insert into cars (id, model, maker, year) values (472, 'Forester', 'Subaru', 2007);
insert into cars (id, model, maker, year) values (473, 'Neon', 'Dodge', 2000);
insert into cars (id, model, maker, year) values (474, '3500', 'Chevrolet', 1993);
insert into cars (id, model, maker, year) values (475, 'Park Avenue', 'Buick', 1999);
insert into cars (id, model, maker, year) values (476, 'Cougar', 'Mercury', 1990);
insert into cars (id, model, maker, year) values (477, 'Corolla', 'Toyota', 1993);
insert into cars (id, model, maker, year) values (478, 'Q7', 'Audi', 2010);
insert into cars (id, model, maker, year) values (479, 'C70', 'Volvo', 2011);
insert into cars (id, model, maker, year) values (480, 'Sprinter 2500', 'Mercedes-Benz', 2011);
insert into cars (id, model, maker, year) values (481, 'Escalade EXT', 'Cadillac', 2002);
insert into cars (id, model, maker, year) values (482, 'Millenia', 'Mazda', 1998);
insert into cars (id, model, maker, year) values (483, 'CL', 'Acura', 1999);
insert into cars (id, model, maker, year) values (484, 'Truck', 'Mitsubishi', 1989);
insert into cars (id, model, maker, year) values (485, 'Firebird', 'Pontiac', 1985);
insert into cars (id, model, maker, year) values (486, 'S-Class', 'Mercedes-Benz', 2001);
insert into cars (id, model, maker, year) values (487, 'H1', 'Hummer', 1994);
insert into cars (id, model, maker, year) values (488, 'Defender 110', 'Land Rover', 1993);
insert into cars (id, model, maker, year) values (489, 'Club Wagon', 'Ford', 1996);
insert into cars (id, model, maker, year) values (490, 'LX', 'Lexus', 2009);
insert into cars (id, model, maker, year) values (491, 'Grand Vitara', 'Suzuki', 2004);
insert into cars (id, model, maker, year) values (492, 'Sierra 1500', 'GMC', 2003);
insert into cars (id, model, maker, year) values (493, 'C30', 'Volvo', 2012);
insert into cars (id, model, maker, year) values (494, 'Acclaim', 'Plymouth', 1992);
insert into cars (id, model, maker, year) values (495, 'Colorado', 'Chevrolet', 2009);
insert into cars (id, model, maker, year) values (496, 'Summit', 'Eagle', 1996);
insert into cars (id, model, maker, year) values (497, 'Vandura G3500', 'GMC', 1996);
insert into cars (id, model, maker, year) values (498, 'Ram 2500', 'Dodge', 2005);
insert into cars (id, model, maker, year) values (499, 'Element', 'Honda', 2010);
insert into cars (id, model, maker, year) values (500, 'Scirocco', 'Volkswagen', 1985);
insert into cars (id, model, maker, year) values (501, 'T100', 'Toyota', 1998);
insert into cars (id, model, maker, year) values (502, 'Impreza', 'Subaru', 1997);
insert into cars (id, model, maker, year) values (503, 'A4', 'Audi', 2003);
insert into cars (id, model, maker, year) values (504, 'Esprit', 'Lotus', 1992);
insert into cars (id, model, maker, year) values (505, '9-5', 'Saab', 1999);
insert into cars (id, model, maker, year) values (506, 'Aveo', 'Chevrolet', 2009);
insert into cars (id, model, maker, year) values (507, 'GTO', 'Pontiac', 2005);
insert into cars (id, model, maker, year) values (508, 'Avenger', 'Dodge', 2012);
insert into cars (id, model, maker, year) values (509, 'Bravada', 'Oldsmobile', 2001);
insert into cars (id, model, maker, year) values (510, 'RX-7', 'Mazda', 1992);
insert into cars (id, model, maker, year) values (511, 'Mustang', 'Ford', 1986);
insert into cars (id, model, maker, year) values (512, 'SLR McLaren', 'Mercedes-Benz', 2005);
insert into cars (id, model, maker, year) values (513, 'GTI', 'Volkswagen', 2012);
insert into cars (id, model, maker, year) values (514, 'Rogue', 'Nissan', 2009);
insert into cars (id, model, maker, year) values (515, 'Mighty Max', 'Mitsubishi', 1995);
insert into cars (id, model, maker, year) values (516, 'Rodeo', 'Isuzu', 1995);
insert into cars (id, model, maker, year) values (517, 'Avenger', 'Dodge', 2011);
insert into cars (id, model, maker, year) values (518, 'Rally Wagon 3500', 'GMC', 1992);
insert into cars (id, model, maker, year) values (519, 'LX', 'Lexus', 1997);
insert into cars (id, model, maker, year) values (520, '600', 'BMW', 1958);
insert into cars (id, model, maker, year) values (521, 'XG300', 'Hyundai', 2001);
insert into cars (id, model, maker, year) values (522, 'EX', 'Infiniti', 2010);
insert into cars (id, model, maker, year) values (523, 'Millenia', 'Mazda', 1999);
insert into cars (id, model, maker, year) values (524, '9000', 'Saab', 1998);
insert into cars (id, model, maker, year) values (525, 'Azure T', 'Bentley', 2010);
insert into cars (id, model, maker, year) values (526, 'Town & Country', 'Chrysler', 2002);
insert into cars (id, model, maker, year) values (527, 'Durango', 'Dodge', 2000);
insert into cars (id, model, maker, year) values (528, 'Classic', 'Chevrolet', 2004);
insert into cars (id, model, maker, year) values (529, 'Raider', 'Mitsubishi', 2007);
insert into cars (id, model, maker, year) values (530, 'Skylark', 'Buick', 1986);
insert into cars (id, model, maker, year) values (531, 'Impreza', 'Subaru', 2000);
insert into cars (id, model, maker, year) values (532, 'Land Cruiser', 'Toyota', 2004);
insert into cars (id, model, maker, year) values (533, 'Bravada', 'Oldsmobile', 1994);
insert into cars (id, model, maker, year) values (534, 'Space', 'Isuzu', 1994);
insert into cars (id, model, maker, year) values (535, 'B-Series Plus', 'Mazda', 1994);
insert into cars (id, model, maker, year) values (536, 'G-Class', 'Mercedes-Benz', 2009);
insert into cars (id, model, maker, year) values (537, '911', 'Porsche', 2010);
insert into cars (id, model, maker, year) values (538, '100', 'Audi', 1989);
insert into cars (id, model, maker, year) values (539, 'Tahoe', 'Chevrolet', 1997);
insert into cars (id, model, maker, year) values (540, 'S-Type', 'Jaguar', 2001);
insert into cars (id, model, maker, year) values (541, '88', 'Oldsmobile', 1998);
insert into cars (id, model, maker, year) values (542, 'Caravan', 'Dodge', 2011);
insert into cars (id, model, maker, year) values (543, '911', 'Porsche', 1997);
insert into cars (id, model, maker, year) values (544, 'Corvette', 'Chevrolet', 1960);
insert into cars (id, model, maker, year) values (545, 'Caravan', 'Dodge', 2012);
insert into cars (id, model, maker, year) values (546, 'Colt', 'Plymouth', 1992);
insert into cars (id, model, maker, year) values (547, '1500 Club Coupe', 'GMC', 1999);
insert into cars (id, model, maker, year) values (548, 'Sonoma Club Coupe', 'GMC', 1994);
insert into cars (id, model, maker, year) values (549, 'H1', 'Hummer', 1999);
insert into cars (id, model, maker, year) values (550, 'Monaro', 'Holden', 2004);
insert into cars (id, model, maker, year) values (551, 'Z3', 'BMW', 2000);
insert into cars (id, model, maker, year) values (552, 'Grand Vitara', 'Suzuki', 2003);
insert into cars (id, model, maker, year) values (553, 'Express 3500', 'Chevrolet', 2005);
insert into cars (id, model, maker, year) values (554, 'Astra', 'Saturn', 2009);
insert into cars (id, model, maker, year) values (555, 'E-Series', 'Ford', 2010);
insert into cars (id, model, maker, year) values (556, 'Intrepid', 'Dodge', 1998);
insert into cars (id, model, maker, year) values (557, 'Element', 'Honda', 2011);
insert into cars (id, model, maker, year) values (558, 'Land Cruiser', 'Toyota', 2003);
insert into cars (id, model, maker, year) values (559, 'Escape', 'Ford', 2003);
insert into cars (id, model, maker, year) values (560, 'Elantra', 'Hyundai', 1996);
insert into cars (id, model, maker, year) values (561, 'XL-7', 'Suzuki', 2006);
insert into cars (id, model, maker, year) values (562, 'Dakota', 'Ram', 2011);
insert into cars (id, model, maker, year) values (563, 'G6', 'Pontiac', 2006);
insert into cars (id, model, maker, year) values (564, 'Savana', 'GMC', 2010);
insert into cars (id, model, maker, year) values (565, 'Patriot', 'Jeep', 2007);
insert into cars (id, model, maker, year) values (566, 'CR-V', 'Honda', 2010);
insert into cars (id, model, maker, year) values (567, 'RX Hybrid', 'Lexus', 2008);
insert into cars (id, model, maker, year) values (568, 'Grand Prix', 'Pontiac', 1962);
insert into cars (id, model, maker, year) values (569, 'Lancer Evolution', 'Mitsubishi', 2003);
insert into cars (id, model, maker, year) values (570, 'G-Series 1500', 'Chevrolet', 1997);
insert into cars (id, model, maker, year) values (571, '100', 'Audi', 1992);
insert into cars (id, model, maker, year) values (572, 'Express 2500', 'Chevrolet', 1996);
insert into cars (id, model, maker, year) values (573, 'Avalon', 'Toyota', 1998);
insert into cars (id, model, maker, year) values (574, 'Savana 1500', 'GMC', 2002);
insert into cars (id, model, maker, year) values (575, 'Regal', 'Buick', 1998);
insert into cars (id, model, maker, year) values (576, 'Lightning', 'Ford', 1994);
insert into cars (id, model, maker, year) values (577, 'Countryman', 'MINI', 2012);
insert into cars (id, model, maker, year) values (578, 'G6', 'Pontiac', 2009);
insert into cars (id, model, maker, year) values (579, 'Mountaineer', 'Mercury', 2009);
insert into cars (id, model, maker, year) values (580, 'RDX', 'Acura', 2012);
insert into cars (id, model, maker, year) values (581, 'Diamante', 'Mitsubishi', 2000);
insert into cars (id, model, maker, year) values (582, 'Tundra', 'Toyota', 2008);
insert into cars (id, model, maker, year) values (583, 'X3', 'BMW', 2004);
insert into cars (id, model, maker, year) values (584, 'Montana', 'Pontiac', 2003);
insert into cars (id, model, maker, year) values (585, 'Catera', 'Cadillac', 1997);
insert into cars (id, model, maker, year) values (586, 'Range Rover', 'Land Rover', 1996);
insert into cars (id, model, maker, year) values (587, 'Savana 2500', 'GMC', 2011);
insert into cars (id, model, maker, year) values (588, 'Lumina APV', 'Chevrolet', 1992);
insert into cars (id, model, maker, year) values (589, 'LeBaron', 'Chrysler', 1993);
insert into cars (id, model, maker, year) values (590, 'Avalanche 2500', 'Chevrolet', 2002);
insert into cars (id, model, maker, year) values (591, 'Nitro', 'Dodge', 2010);
insert into cars (id, model, maker, year) values (592, 'Aveo', 'Chevrolet', 2006);
insert into cars (id, model, maker, year) values (593, 'Avalanche 1500', 'Chevrolet', 2006);
insert into cars (id, model, maker, year) values (594, '2500 Club Coupe', 'GMC', 1992);
insert into cars (id, model, maker, year) values (595, 'Clubman', 'MINI', 2012);
insert into cars (id, model, maker, year) values (596, 'S-Class', 'Mercedes-Benz', 2002);
insert into cars (id, model, maker, year) values (597, 'STS', 'Cadillac', 2007);
insert into cars (id, model, maker, year) values (598, 'Dakota Club', 'Dodge', 1995);
insert into cars (id, model, maker, year) values (599, 'Monte Carlo', 'Chevrolet', 2001);
insert into cars (id, model, maker, year) values (600, 'Journey', 'Dodge', 2011);
insert into cars (id, model, maker, year) values (601, 'Century', 'Buick', 2000);
insert into cars (id, model, maker, year) values (602, '530', 'BMW', 2001);
insert into cars (id, model, maker, year) values (603, 'Tracker', 'Chevrolet', 2002);
insert into cars (id, model, maker, year) values (604, 'Mazda6', 'Mazda', 2012);
insert into cars (id, model, maker, year) values (605, 'RX-7', 'Mazda', 1985);
insert into cars (id, model, maker, year) values (606, 'Q7', 'Audi', 2007);
insert into cars (id, model, maker, year) values (607, 'Tahoe', 'Chevrolet', 2006);
insert into cars (id, model, maker, year) values (608, 'Fusion', 'Ford', 2007);
insert into cars (id, model, maker, year) values (609, 'DB9', 'Aston Martin', 2012);
insert into cars (id, model, maker, year) values (610, 'Rodeo', 'Isuzu', 2001);
insert into cars (id, model, maker, year) values (611, 'LeSabre', 'Buick', 1996);
insert into cars (id, model, maker, year) values (612, 'Outback', 'Subaru', 2005);
insert into cars (id, model, maker, year) values (613, 'MX-5', 'Mazda', 1991);
insert into cars (id, model, maker, year) values (614, 'Sonata', 'Hyundai', 2002);
insert into cars (id, model, maker, year) values (615, 'Expedition', 'Ford', 2000);
insert into cars (id, model, maker, year) values (616, 'Crown Victoria', 'Ford', 2001);
insert into cars (id, model, maker, year) values (617, '8 Series', 'BMW', 1995);
insert into cars (id, model, maker, year) values (618, 'F250', 'Ford', 1992);
insert into cars (id, model, maker, year) values (619, 'Mark VII', 'Lincoln', 1992);
insert into cars (id, model, maker, year) values (620, 'Sentra', 'Nissan', 2012);
insert into cars (id, model, maker, year) values (621, 'Ram 3500', 'Dodge', 2002);
insert into cars (id, model, maker, year) values (622, 'Accent', 'Hyundai', 2000);
insert into cars (id, model, maker, year) values (623, 'DeVille', 'Cadillac', 2004);
insert into cars (id, model, maker, year) values (624, 'Impala', 'Chevrolet', 2012);
insert into cars (id, model, maker, year) values (625, 'Dakota Club', 'Dodge', 2007);
insert into cars (id, model, maker, year) values (626, '1500', 'Chevrolet', 1993);
insert into cars (id, model, maker, year) values (627, 'Quest', 'Nissan', 2005);
insert into cars (id, model, maker, year) values (628, 'MDX', 'Acura', 2009);
insert into cars (id, model, maker, year) values (629, 'Accent', 'Hyundai', 2005);
insert into cars (id, model, maker, year) values (630, '240SX', 'Nissan', 1992);
insert into cars (id, model, maker, year) values (631, 'Bonneville', 'Pontiac', 1999);
insert into cars (id, model, maker, year) values (632, 'SJ', 'Suzuki', 1986);
insert into cars (id, model, maker, year) values (633, 'Savana 3500', 'GMC', 1997);
insert into cars (id, model, maker, year) values (634, 'Q', 'Infiniti', 2000);
insert into cars (id, model, maker, year) values (635, 'Outlook', 'Saturn', 2008);
insert into cars (id, model, maker, year) values (636, 'Talon', 'Eagle', 1994);
insert into cars (id, model, maker, year) values (637, 'Golf', 'Volkswagen', 1996);
insert into cars (id, model, maker, year) values (638, 'G25', 'Infiniti', 2011);
insert into cars (id, model, maker, year) values (639, 'Mazda6', 'Mazda', 2008);
insert into cars (id, model, maker, year) values (640, 'Bravada', 'Oldsmobile', 2000);
insert into cars (id, model, maker, year) values (641, 'Intrepid', 'Dodge', 2003);
insert into cars (id, model, maker, year) values (642, 'Corolla', 'Toyota', 2010);
insert into cars (id, model, maker, year) values (643, 'Taurus', 'Ford', 2009);
insert into cars (id, model, maker, year) values (644, 'XJ Series', 'Jaguar', 2001);
insert into cars (id, model, maker, year) values (645, 'FJ Cruiser', 'Toyota', 2009);
insert into cars (id, model, maker, year) values (646, 'MDX', 'Acura', 2003);
insert into cars (id, model, maker, year) values (647, 'Skylark', 'Buick', 1987);
insert into cars (id, model, maker, year) values (648, 'Cobalt', 'Chevrolet', 2010);
insert into cars (id, model, maker, year) values (649, 'Land Cruiser', 'Toyota', 2007);
insert into cars (id, model, maker, year) values (650, 'Suburban 1500', 'Chevrolet', 2008);
insert into cars (id, model, maker, year) values (651, 'GTI', 'Volkswagen', 1996);
insert into cars (id, model, maker, year) values (652, 'Crown Victoria', 'Ford', 1993);
insert into cars (id, model, maker, year) values (653, 'B-Series', 'Mazda', 2000);
insert into cars (id, model, maker, year) values (654, 'Grand Caravan', 'Dodge', 1992);
insert into cars (id, model, maker, year) values (655, 'Pajero', 'Mitsubishi', 1992);
insert into cars (id, model, maker, year) values (656, '6 Series', 'BMW', 2007);
insert into cars (id, model, maker, year) values (657, 'Dakota', 'Dodge', 1995);
insert into cars (id, model, maker, year) values (658, 'E250', 'Ford', 2007);
insert into cars (id, model, maker, year) values (659, 'G35', 'Infiniti', 2008);
insert into cars (id, model, maker, year) values (660, 'Town & Country', 'Chrysler', 2009);
insert into cars (id, model, maker, year) values (661, 'G-Series 1500', 'Chevrolet', 1996);
insert into cars (id, model, maker, year) values (662, 'Topaz', 'Mercury', 1989);
insert into cars (id, model, maker, year) values (663, 'Mark LT', 'Lincoln', 2008);
insert into cars (id, model, maker, year) values (664, 'Forester', 'Subaru', 2007);
insert into cars (id, model, maker, year) values (665, 'RAV4', 'Toyota', 2008);
insert into cars (id, model, maker, year) values (666, 'Previa', 'Toyota', 1994);
insert into cars (id, model, maker, year) values (667, 'Montero', 'Mitsubishi', 1996);
insert into cars (id, model, maker, year) values (668, 'LX', 'Lexus', 2003);
insert into cars (id, model, maker, year) values (669, 'Swift', 'Suzuki', 2000);
insert into cars (id, model, maker, year) values (670, 'Explorer', 'Ford', 1991);
insert into cars (id, model, maker, year) values (671, 'Grand Caravan', 'Dodge', 2010);
insert into cars (id, model, maker, year) values (672, 'ES', 'Lexus', 2009);
insert into cars (id, model, maker, year) values (673, 'Allroad', 'Audi', 2001);
insert into cars (id, model, maker, year) values (674, 'Civic', 'Honda', 1996);
insert into cars (id, model, maker, year) values (675, 'LTD', 'Ford', 1985);
insert into cars (id, model, maker, year) values (676, 'Journey', 'Dodge', 2011);
insert into cars (id, model, maker, year) values (677, 'STS', 'Cadillac', 2006);
insert into cars (id, model, maker, year) values (678, 'PT Cruiser', 'Chrysler', 2007);
insert into cars (id, model, maker, year) values (679, 'Defender 110', 'Land Rover', 1993);
insert into cars (id, model, maker, year) values (680, 'Frontier', 'Nissan', 1999);
insert into cars (id, model, maker, year) values (681, 'Sorento', 'Kia', 2006);
insert into cars (id, model, maker, year) values (682, 'Fleetwood', 'Cadillac', 1993);
insert into cars (id, model, maker, year) values (683, '57', 'Maybach', 2005);
insert into cars (id, model, maker, year) values (684, 'Continental GT', 'Bentley', 2012);
insert into cars (id, model, maker, year) values (685, 'Impala', 'Chevrolet', 2012);
insert into cars (id, model, maker, year) values (686, 'Suburban 2500', 'Chevrolet', 2004);
insert into cars (id, model, maker, year) values (687, 'Tracker', 'Chevrolet', 2002);
insert into cars (id, model, maker, year) values (688, 'Alero', 'Oldsmobile', 1999);
insert into cars (id, model, maker, year) values (689, 'Wrangler', 'Jeep', 1995);
insert into cars (id, model, maker, year) values (690, 'Classic', 'Chevrolet', 2005);
insert into cars (id, model, maker, year) values (691, 'RAV4', 'Toyota', 2004);
insert into cars (id, model, maker, year) values (692, 'Swift', 'Suzuki', 1989);
insert into cars (id, model, maker, year) values (693, 'CTS', 'Cadillac', 2003);
insert into cars (id, model, maker, year) values (694, 'Laser', 'Ford', 1986);
insert into cars (id, model, maker, year) values (695, 'Town Car', 'Lincoln', 1993);
insert into cars (id, model, maker, year) values (696, '3 Series', 'BMW', 2006);
insert into cars (id, model, maker, year) values (697, 'Rally Wagon 3500', 'GMC', 1993);
insert into cars (id, model, maker, year) values (698, 'LeSabre', 'Buick', 1998);
insert into cars (id, model, maker, year) values (699, 'Galant', 'Mitsubishi', 1995);
insert into cars (id, model, maker, year) values (700, 'TundraMax', 'Toyota', 2007);
insert into cars (id, model, maker, year) values (701, 'RX', 'Lexus', 2013);
insert into cars (id, model, maker, year) values (702, 'Cougar', 'Mercury', 1994);
insert into cars (id, model, maker, year) values (703, '911', 'Porsche', 2011);
insert into cars (id, model, maker, year) values (704, '88', 'Oldsmobile', 1999);
insert into cars (id, model, maker, year) values (705, 'Cirrus', 'Chrysler', 1995);
insert into cars (id, model, maker, year) values (706, 'Impala SS', 'Chevrolet', 1994);
insert into cars (id, model, maker, year) values (707, '944', 'Porsche', 1989);
insert into cars (id, model, maker, year) values (708, 'Crown Victoria', 'Ford', 2005);
insert into cars (id, model, maker, year) values (709, 'E-Class', 'Mercedes-Benz', 2004);
insert into cars (id, model, maker, year) values (710, 'Ram Van 1500', 'Dodge', 2003);
insert into cars (id, model, maker, year) values (711, 'Ram Van 3500', 'Dodge', 1995);
insert into cars (id, model, maker, year) values (712, '612 Scaglietti', 'Ferrari', 2008);
insert into cars (id, model, maker, year) values (713, 'M6', 'BMW', 2010);
insert into cars (id, model, maker, year) values (714, 'Corvette', 'Chevrolet', 2006);
insert into cars (id, model, maker, year) values (715, 'Optima', 'Kia', 2011);
insert into cars (id, model, maker, year) values (716, 'Tundra', 'Toyota', 2001);
insert into cars (id, model, maker, year) values (717, 'Tempest', 'Pontiac', 1967);
insert into cars (id, model, maker, year) values (718, 'Corvette', 'Chevrolet', 1973);
insert into cars (id, model, maker, year) values (719, 'Venture', 'Chevrolet', 2005);
insert into cars (id, model, maker, year) values (720, 'Corvette', 'Chevrolet', 2002);
insert into cars (id, model, maker, year) values (721, 'Wrangler', 'Jeep', 2003);
insert into cars (id, model, maker, year) values (722, 'Grand Caravan', 'Dodge', 1992);
insert into cars (id, model, maker, year) values (723, 'Villager', 'Mercury', 2000);
insert into cars (id, model, maker, year) values (724, 'Range Rover', 'Land Rover', 1998);
insert into cars (id, model, maker, year) values (725, 'Wrangler', 'Jeep', 1998);
insert into cars (id, model, maker, year) values (726, 'Sebring', 'Chrysler', 2010);
insert into cars (id, model, maker, year) values (727, 'X-Type', 'Jaguar', 2008);
insert into cars (id, model, maker, year) values (728, 'Q7', 'Audi', 2010);
insert into cars (id, model, maker, year) values (729, 'Metro', 'Chevrolet', 1999);
insert into cars (id, model, maker, year) values (730, 'Envoy', 'GMC', 2009);
insert into cars (id, model, maker, year) values (731, 'Capri', 'Mercury', 1991);
insert into cars (id, model, maker, year) values (732, 'RL', 'Acura', 2005);
insert into cars (id, model, maker, year) values (733, 'M Roadster', 'BMW', 2006);
insert into cars (id, model, maker, year) values (734, '928', 'Porsche', 1989);
insert into cars (id, model, maker, year) values (735, 'E-Class', 'Mercedes-Benz', 1992);
insert into cars (id, model, maker, year) values (736, 'Continental GT', 'Bentley', 2010);
insert into cars (id, model, maker, year) values (737, '62', 'Maybach', 2012);
insert into cars (id, model, maker, year) values (738, 'Safari', 'GMC', 1995);
insert into cars (id, model, maker, year) values (739, 'Neon', 'Dodge', 1999);
insert into cars (id, model, maker, year) values (740, 'B-Series', 'Mazda', 1994);
insert into cars (id, model, maker, year) values (741, 'G-Series 2500', 'Chevrolet', 1998);
insert into cars (id, model, maker, year) values (742, 'Navajo', 'Mazda', 1991);
insert into cars (id, model, maker, year) values (743, 'Ram 1500 Club', 'Dodge', 1999);
insert into cars (id, model, maker, year) values (744, '5000CS', 'Audi', 1987);
insert into cars (id, model, maker, year) values (745, 'SLK-Class', 'Mercedes-Benz', 2012);
insert into cars (id, model, maker, year) values (746, '968', 'Porsche', 1992);
insert into cars (id, model, maker, year) values (747, 'Lancer', 'Mitsubishi', 2002);
insert into cars (id, model, maker, year) values (748, 'Continental GTC', 'Bentley', 2007);
insert into cars (id, model, maker, year) values (749, 'Diamante', 'Mitsubishi', 1994);
insert into cars (id, model, maker, year) values (750, 'Element', 'Honda', 2003);
insert into cars (id, model, maker, year) values (751, 'S80', 'Volvo', 2007);
insert into cars (id, model, maker, year) values (752, 'Mazda5', 'Mazda', 2008);
insert into cars (id, model, maker, year) values (753, 'LTD Crown Victoria', 'Ford', 1986);
insert into cars (id, model, maker, year) values (754, 'S4', 'Audi', 2007);
insert into cars (id, model, maker, year) values (755, 'Town & Country', 'Chrysler', 2011);
insert into cars (id, model, maker, year) values (756, 'LS', 'Lexus', 1990);
insert into cars (id, model, maker, year) values (757, 'Swift', 'Suzuki', 1992);
insert into cars (id, model, maker, year) values (758, 'Golf', 'Volkswagen', 1999);
insert into cars (id, model, maker, year) values (759, 'Toronado', 'Oldsmobile', 1992);
insert into cars (id, model, maker, year) values (760, 'A8', 'Audi', 2002);
insert into cars (id, model, maker, year) values (761, 'Tredia', 'Mitsubishi', 1987);
insert into cars (id, model, maker, year) values (762, '9-7X', 'Saab', 2007);
insert into cars (id, model, maker, year) values (763, 'G-Series G30', 'Chevrolet', 1995);
insert into cars (id, model, maker, year) values (764, 'Vibe', 'Pontiac', 2005);
insert into cars (id, model, maker, year) values (765, 'Pajero', 'Mitsubishi', 1997);
insert into cars (id, model, maker, year) values (766, 'Savana 2500', 'GMC', 2006);
insert into cars (id, model, maker, year) values (767, 'C-Class', 'Mercedes-Benz', 1993);
insert into cars (id, model, maker, year) values (768, 'Cavalier', 'Chevrolet', 1998);
insert into cars (id, model, maker, year) values (769, 'Accord', 'Honda', 1990);
insert into cars (id, model, maker, year) values (770, 'Escape', 'Ford', 2010);
insert into cars (id, model, maker, year) values (771, 'Outback', 'Subaru', 2011);
insert into cars (id, model, maker, year) values (772, '98', 'Oldsmobile', 1996);
insert into cars (id, model, maker, year) values (773, 'LS', 'Lexus', 1998);
insert into cars (id, model, maker, year) values (774, 'Jetta', 'Volkswagen', 2005);
insert into cars (id, model, maker, year) values (775, 'Leone', 'Subaru', 1987);
insert into cars (id, model, maker, year) values (776, '6 Series', 'BMW', 2006);
insert into cars (id, model, maker, year) values (777, 'Econoline E150', 'Ford', 1993);
insert into cars (id, model, maker, year) values (778, 'MPV', 'Mazda', 2004);
insert into cars (id, model, maker, year) values (779, 'Optima', 'Kia', 2001);
insert into cars (id, model, maker, year) values (780, 'Sportage', 'Kia', 2011);
insert into cars (id, model, maker, year) values (781, 'CR-V', 'Honda', 2009);
insert into cars (id, model, maker, year) values (782, 'Highlander', 'Toyota', 2001);
insert into cars (id, model, maker, year) values (783, 'Prius v', 'Toyota', 2012);
insert into cars (id, model, maker, year) values (784, 'H2', 'Hummer', 2009);
insert into cars (id, model, maker, year) values (785, 'IS', 'Lexus', 2007);
insert into cars (id, model, maker, year) values (786, 'Sunfire', 'Pontiac', 2005);
insert into cars (id, model, maker, year) values (787, 'Ram 1500', 'Dodge', 1999);
insert into cars (id, model, maker, year) values (788, 'Fusion', 'Ford', 2008);
insert into cars (id, model, maker, year) values (789, 'Mazda6', 'Mazda', 2011);
insert into cars (id, model, maker, year) values (790, 'LS', 'Lexus', 1999);
insert into cars (id, model, maker, year) values (791, 'Golf', 'Volkswagen', 2004);
insert into cars (id, model, maker, year) values (792, 'Grand Caravan', 'Dodge', 1996);
insert into cars (id, model, maker, year) values (793, 'Previa', 'Toyota', 1997);
insert into cars (id, model, maker, year) values (794, 'Accord', 'Honda', 1988);
insert into cars (id, model, maker, year) values (795, 'Neon', 'Dodge', 2004);
insert into cars (id, model, maker, year) values (796, 'SRX', 'Cadillac', 2010);
insert into cars (id, model, maker, year) values (797, 'Sable', 'Mercury', 1996);
insert into cars (id, model, maker, year) values (798, '240SX', 'Nissan', 1997);
insert into cars (id, model, maker, year) values (799, 'MPV', 'Mazda', 2002);
insert into cars (id, model, maker, year) values (800, 'Sentra', 'Nissan', 2000);
insert into cars (id, model, maker, year) values (801, '300D', 'Mercedes-Benz', 1992);
insert into cars (id, model, maker, year) values (802, 'Scirocco', 'Volkswagen', 1986);
insert into cars (id, model, maker, year) values (803, 'Q5', 'Audi', 2010);
insert into cars (id, model, maker, year) values (804, 'XC90', 'Volvo', 2012);
insert into cars (id, model, maker, year) values (805, 'Cabriolet', 'Volkswagen', 1987);
insert into cars (id, model, maker, year) values (806, 'Suburban 2500', 'Chevrolet', 2006);
insert into cars (id, model, maker, year) values (807, 'Courier', 'Ford', 1989);
insert into cars (id, model, maker, year) values (808, 'A4', 'Audi', 1997);
insert into cars (id, model, maker, year) values (809, 'Vigor', 'Acura', 1994);
insert into cars (id, model, maker, year) values (810, 'Seville', 'Cadillac', 2000);
insert into cars (id, model, maker, year) values (811, 'Tundra', 'Toyota', 2004);
insert into cars (id, model, maker, year) values (812, 'Xterra', 'Nissan', 2012);
insert into cars (id, model, maker, year) values (813, 'Navigator', 'Lincoln', 1998);
insert into cars (id, model, maker, year) values (814, 'i-280', 'Isuzu', 2006);
insert into cars (id, model, maker, year) values (815, 'Express 2500', 'Chevrolet', 1999);
insert into cars (id, model, maker, year) values (816, 'Envoy XL', 'GMC', 2005);
insert into cars (id, model, maker, year) values (817, 'Traverse', 'Chevrolet', 2010);
insert into cars (id, model, maker, year) values (818, 'Dakota Club', 'Dodge', 2000);
insert into cars (id, model, maker, year) values (819, '4Runner', 'Toyota', 2012);
insert into cars (id, model, maker, year) values (820, 'MPV', 'Mazda', 2000);
insert into cars (id, model, maker, year) values (821, 'CLK-Class', 'Mercedes-Benz', 2000);
insert into cars (id, model, maker, year) values (822, 'Impala', 'Chevrolet', 1994);
insert into cars (id, model, maker, year) values (823, 'Thunderbird', 'Ford', 1965);
insert into cars (id, model, maker, year) values (824, 'Firebird', 'Pontiac', 2001);
insert into cars (id, model, maker, year) values (825, 'Yaris', 'Toyota', 2007);
insert into cars (id, model, maker, year) values (826, 'Endeavor', 'Mitsubishi', 2005);
insert into cars (id, model, maker, year) values (827, 'Avenger', 'Dodge', 2000);
insert into cars (id, model, maker, year) values (828, 'Eurovan', 'Volkswagen', 1997);
insert into cars (id, model, maker, year) values (829, 'IS', 'Lexus', 2011);
insert into cars (id, model, maker, year) values (830, 'Grand Prix', 'Pontiac', 2007);
insert into cars (id, model, maker, year) values (831, 'Tacoma', 'Toyota', 2000);
insert into cars (id, model, maker, year) values (832, 'B-Series Plus', 'Mazda', 1999);
insert into cars (id, model, maker, year) values (833, 'Outback', 'Subaru', 2002);
insert into cars (id, model, maker, year) values (834, 'Cabriolet', 'Audi', 1998);
insert into cars (id, model, maker, year) values (835, 'Silverado', 'Chevrolet', 2010);
insert into cars (id, model, maker, year) values (836, 'Explorer', 'Ford', 1995);
insert into cars (id, model, maker, year) values (837, 'Galant', 'Mitsubishi', 1998);
insert into cars (id, model, maker, year) values (838, 'Civic', 'Honda', 2004);
insert into cars (id, model, maker, year) values (839, 'Genesis', 'Hyundai', 2012);
insert into cars (id, model, maker, year) values (840, 'Cayenne', 'Porsche', 2006);
insert into cars (id, model, maker, year) values (841, 'Passat', 'Volkswagen', 2007);
insert into cars (id, model, maker, year) values (842, 'LS', 'Lexus', 2005);
insert into cars (id, model, maker, year) values (843, 'R8', 'Audi', 2008);
insert into cars (id, model, maker, year) values (844, 'Sportage', 'Kia', 2011);
insert into cars (id, model, maker, year) values (845, 'Taurus', 'Ford', 2007);
insert into cars (id, model, maker, year) values (846, 'Park Avenue', 'Buick', 1994);
insert into cars (id, model, maker, year) values (847, 'Tahoe', 'Chevrolet', 1996);
insert into cars (id, model, maker, year) values (848, 'Lanos', 'Daewoo', 2002);
insert into cars (id, model, maker, year) values (849, 'Equus', 'Hyundai', 2013);
insert into cars (id, model, maker, year) values (850, 'GS', 'Lexus', 2003);
insert into cars (id, model, maker, year) values (851, 'GTI', 'Volkswagen', 1990);
insert into cars (id, model, maker, year) values (852, 'GL-Class', 'Mercedes-Benz', 2009);
insert into cars (id, model, maker, year) values (853, 'Forenza', 'Suzuki', 2006);
insert into cars (id, model, maker, year) values (854, 'F350', 'Ford', 2000);
insert into cars (id, model, maker, year) values (855, 'Regal', 'Buick', 1990);
insert into cars (id, model, maker, year) values (856, 'Silverado 1500', 'Chevrolet', 2000);
insert into cars (id, model, maker, year) values (857, 'Suburban 1500', 'Chevrolet', 2009);
insert into cars (id, model, maker, year) values (858, 'G', 'Infiniti', 2011);
insert into cars (id, model, maker, year) values (859, 'F250', 'Ford', 2000);
insert into cars (id, model, maker, year) values (860, 'Grand Cherokee', 'Jeep', 1993);
insert into cars (id, model, maker, year) values (861, 'M3', 'BMW', 2009);
insert into cars (id, model, maker, year) values (862, 'E-Class', 'Mercedes-Benz', 1989);
insert into cars (id, model, maker, year) values (863, 'Park Avenue', 'Buick', 2004);
insert into cars (id, model, maker, year) values (864, 'Express 2500', 'Chevrolet', 2003);
insert into cars (id, model, maker, year) values (865, 'LeSabre', 'Buick', 1990);
insert into cars (id, model, maker, year) values (866, 'F350', 'Ford', 2004);
insert into cars (id, model, maker, year) values (867, 'Mustang', 'Ford', 1965);
insert into cars (id, model, maker, year) values (868, 'Corvette', 'Chevrolet', 2011);
insert into cars (id, model, maker, year) values (869, 'Sidekick', 'Suzuki', 1995);
insert into cars (id, model, maker, year) values (870, 'Crossfire', 'Chrysler', 2005);
insert into cars (id, model, maker, year) values (871, 'Bonneville', 'Pontiac', 1996);
insert into cars (id, model, maker, year) values (872, 'Talon', 'Eagle', 1995);
insert into cars (id, model, maker, year) values (873, 'Accord', 'Honda', 2008);
insert into cars (id, model, maker, year) values (874, 'Celica', 'Toyota', 1998);
insert into cars (id, model, maker, year) values (875, 'Esteem', 'Suzuki', 1998);
insert into cars (id, model, maker, year) values (876, 'Pilot', 'Honda', 2004);
insert into cars (id, model, maker, year) values (877, 'Daewoo Kalos', 'Pontiac', 2005);
insert into cars (id, model, maker, year) values (878, 'Eclipse', 'Mitsubishi', 2007);
insert into cars (id, model, maker, year) values (879, 'LR2', 'Land Rover', 2010);
insert into cars (id, model, maker, year) values (880, 'Suburban 2500', 'Chevrolet', 1993);
insert into cars (id, model, maker, year) values (881, 'A4', 'Audi', 2009);
insert into cars (id, model, maker, year) values (882, 'Z4 M Roadster', 'BMW', 2009);
insert into cars (id, model, maker, year) values (883, 'Express 3500', 'Chevrolet', 2011);
insert into cars (id, model, maker, year) values (884, 'Pajero', 'Mitsubishi', 2001);
insert into cars (id, model, maker, year) values (885, 'Bronco II', 'Ford', 1985);
insert into cars (id, model, maker, year) values (886, 'Sentra', 'Nissan', 2001);
insert into cars (id, model, maker, year) values (887, '1500', 'GMC', 1992);
insert into cars (id, model, maker, year) values (888, 'Sedona', 'Kia', 2012);
insert into cars (id, model, maker, year) values (889, 'Sequoia', 'Toyota', 2005);
insert into cars (id, model, maker, year) values (890, 'Electra', 'Buick', 1990);
insert into cars (id, model, maker, year) values (891, 'Firefly', 'Pontiac', 1989);
insert into cars (id, model, maker, year) values (892, 'Range Rover Sport', 'Land Rover', 2012);
insert into cars (id, model, maker, year) values (893, 'Amigo', 'Isuzu', 1998);
insert into cars (id, model, maker, year) values (894, 'Malibu', 'Chevrolet', 2004);
insert into cars (id, model, maker, year) values (895, 'MPV', 'Mazda', 1995);
insert into cars (id, model, maker, year) values (896, 'Viper', 'Dodge', 2000);
insert into cars (id, model, maker, year) values (897, 'CTS', 'Cadillac', 2012);
insert into cars (id, model, maker, year) values (898, '5000S', 'Audi', 1987);
insert into cars (id, model, maker, year) values (899, 'M', 'Infiniti', 2007);
insert into cars (id, model, maker, year) values (900, '190E', 'Mercedes-Benz', 1993);
insert into cars (id, model, maker, year) values (901, 'ES', 'Lexus', 2000);
insert into cars (id, model, maker, year) values (902, 'Express 2500', 'Chevrolet', 2001);
insert into cars (id, model, maker, year) values (903, 'Jetta', 'Volkswagen', 1997);
insert into cars (id, model, maker, year) values (904, 'Rally Wagon 3500', 'GMC', 1993);
insert into cars (id, model, maker, year) values (905, 'New Beetle', 'Volkswagen', 2002);
insert into cars (id, model, maker, year) values (906, 'Arnage', 'Bentley', 2005);
insert into cars (id, model, maker, year) values (907, 'Trans Sport', 'Pontiac', 1996);
insert into cars (id, model, maker, year) values (908, 'Ram 1500 Club', 'Dodge', 1996);
insert into cars (id, model, maker, year) values (909, 'Breeze', 'Plymouth', 1996);
insert into cars (id, model, maker, year) values (910, 'Corvette', 'Chevrolet', 1989);
insert into cars (id, model, maker, year) values (911, 'Camaro', 'Chevrolet', 1982);
insert into cars (id, model, maker, year) values (912, '7 Series', 'BMW', 1994);
insert into cars (id, model, maker, year) values (913, 'F-Series', 'Ford', 2006);
insert into cars (id, model, maker, year) values (914, 'VS Commodore', 'Holden', 1997);
insert into cars (id, model, maker, year) values (915, 'Rogue', 'Nissan', 2009);
insert into cars (id, model, maker, year) values (916, 'Prius', 'Toyota', 2008);
insert into cars (id, model, maker, year) values (917, 'Type 2', 'Volkswagen', 1990);
insert into cars (id, model, maker, year) values (918, 'F-Series', 'Ford', 2002);
insert into cars (id, model, maker, year) values (919, 'F-Series', 'Ford', 1988);
insert into cars (id, model, maker, year) values (920, 'Sable', 'Mercury', 2009);
insert into cars (id, model, maker, year) values (921, 'Tempest', 'Pontiac', 1961);
insert into cars (id, model, maker, year) values (922, 'Pathfinder', 'Nissan', 2009);
insert into cars (id, model, maker, year) values (923, 'Challenger', 'Mitsubishi', 2001);
insert into cars (id, model, maker, year) values (924, '300M', 'Chrysler', 2003);
insert into cars (id, model, maker, year) values (925, 'GTI', 'Volkswagen', 1996);
insert into cars (id, model, maker, year) values (926, 'Rodeo', 'Isuzu', 1995);
insert into cars (id, model, maker, year) values (927, 'MR2', 'Toyota', 1994);
insert into cars (id, model, maker, year) values (928, 'SLX', 'Acura', 1997);
insert into cars (id, model, maker, year) values (929, 'Suburban 2500', 'Chevrolet', 1992);
insert into cars (id, model, maker, year) values (930, '400E', 'Mercedes-Benz', 1993);
insert into cars (id, model, maker, year) values (931, 'MGB', 'MG', 1977);
insert into cars (id, model, maker, year) values (932, 'E150', 'Ford', 2007);
insert into cars (id, model, maker, year) values (933, 'E-Series', 'Ford', 2011);
insert into cars (id, model, maker, year) values (934, '9-5', 'Saab', 2001);
insert into cars (id, model, maker, year) values (935, 'Outlander', 'Mitsubishi', 2008);
insert into cars (id, model, maker, year) values (936, 'GT500', 'Ford', 2009);
insert into cars (id, model, maker, year) values (937, 'Mustang', 'Ford', 2011);
insert into cars (id, model, maker, year) values (938, 'V8 Vantage', 'Aston Martin', 2011);
insert into cars (id, model, maker, year) values (939, 'Bonneville', 'Pontiac', 1991);
insert into cars (id, model, maker, year) values (940, 'Fifth Ave', 'Chrysler', 1993);
insert into cars (id, model, maker, year) values (941, 'E-Series', 'Ford', 2005);
insert into cars (id, model, maker, year) values (942, 'S4', 'Audi', 2001);
insert into cars (id, model, maker, year) values (943, 'S60', 'Volvo', 2006);
insert into cars (id, model, maker, year) values (944, 'RX-7', 'Mazda', 1993);
insert into cars (id, model, maker, year) values (945, 'Grand Am', 'Pontiac', 1987);
insert into cars (id, model, maker, year) values (946, 'Escalade EXT', 'Cadillac', 2007);
insert into cars (id, model, maker, year) values (947, 'Grand Caravan', 'Dodge', 1994);
insert into cars (id, model, maker, year) values (948, 'Galant', 'Mitsubishi', 1996);
insert into cars (id, model, maker, year) values (949, 'Sonoma', 'GMC', 1997);
insert into cars (id, model, maker, year) values (950, '911', 'Porsche', 1989);
insert into cars (id, model, maker, year) values (951, 'Firefly', 'Pontiac', 1992);
insert into cars (id, model, maker, year) values (952, 'Prizm', 'Geo', 1996);
insert into cars (id, model, maker, year) values (953, 'Cougar', 'Mercury', 1967);
insert into cars (id, model, maker, year) values (954, 'Continental', 'Lincoln', 1987);
insert into cars (id, model, maker, year) values (955, 'tC', 'Scion', 2006);
insert into cars (id, model, maker, year) values (956, 'F-Series', 'Ford', 2007);
insert into cars (id, model, maker, year) values (957, 'S-Class', 'Mercedes-Benz', 1985);
insert into cars (id, model, maker, year) values (958, 'S-Series', 'Saturn', 1999);
insert into cars (id, model, maker, year) values (959, 'Yaris', 'Toyota', 2008);
insert into cars (id, model, maker, year) values (960, 'Grand Prix Turbo', 'Pontiac', 1990);
insert into cars (id, model, maker, year) values (961, 'Yukon XL 1500', 'GMC', 2005);
insert into cars (id, model, maker, year) values (962, 'GS', 'Lexus', 2013);
insert into cars (id, model, maker, year) values (963, 'Ranger', 'Ford', 1993);
insert into cars (id, model, maker, year) values (964, 'S80', 'Volvo', 2004);
insert into cars (id, model, maker, year) values (965, 'TSX', 'Acura', 2005);
insert into cars (id, model, maker, year) values (966, 'Navigator', 'Lincoln', 1999);
insert into cars (id, model, maker, year) values (967, 'Murciélago', 'Lamborghini', 2009);
insert into cars (id, model, maker, year) values (968, 'C30', 'Volvo', 2012);
insert into cars (id, model, maker, year) values (969, 'Patriot', 'Jeep', 2009);
insert into cars (id, model, maker, year) values (970, 'Mazda3', 'Mazda', 2009);
insert into cars (id, model, maker, year) values (971, 'Taurus', 'Ford', 2003);
insert into cars (id, model, maker, year) values (972, 'A6', 'Audi', 1999);
insert into cars (id, model, maker, year) values (973, '300ZX', 'Nissan', 1995);
insert into cars (id, model, maker, year) values (974, 'G', 'Infiniti', 1993);
insert into cars (id, model, maker, year) values (975, 'Sky', 'Saturn', 2007);
insert into cars (id, model, maker, year) values (976, '1500 Club Coupe', 'GMC', 1995);
insert into cars (id, model, maker, year) values (977, 'Taurus', 'Ford', 1993);
insert into cars (id, model, maker, year) values (978, 'MX-5', 'Mazda', 2011);
insert into cars (id, model, maker, year) values (979, 'Mazda6', 'Mazda', 2013);
insert into cars (id, model, maker, year) values (980, 'Forte', 'Kia', 2010);
insert into cars (id, model, maker, year) values (981, 'STS', 'Cadillac', 2011);
insert into cars (id, model, maker, year) values (982, '911', 'Porsche', 2000);
insert into cars (id, model, maker, year) values (983, 'Laser', 'Ford', 1984);
insert into cars (id, model, maker, year) values (984, '3 Series', 'BMW', 2001);
insert into cars (id, model, maker, year) values (985, '750', 'BMW', 2006);
insert into cars (id, model, maker, year) values (986, 'LHS', 'Chrysler', 1997);
insert into cars (id, model, maker, year) values (987, 'R32', 'Volkswagen', 2004);
insert into cars (id, model, maker, year) values (988, 'Rodeo', 'Isuzu', 1993);
insert into cars (id, model, maker, year) values (989, 'Highlander', 'Toyota', 2009);
insert into cars (id, model, maker, year) values (990, 'Santa Fe', 'Hyundai', 2004);
insert into cars (id, model, maker, year) values (991, '90', 'Audi', 1994);
insert into cars (id, model, maker, year) values (992, 'Frontier', 'Nissan', 2011);
insert into cars (id, model, maker, year) values (993, 'H3', 'Hummer', 2007);
insert into cars (id, model, maker, year) values (994, 'Camry', 'Toyota', 2005);
insert into cars (id, model, maker, year) values (995, 'Charger', 'Dodge', 2010);
insert into cars (id, model, maker, year) values (996, 'Suburban 1500', 'Chevrolet', 2004);
insert into cars (id, model, maker, year) values (997, 'CL-Class', 'Mercedes-Benz', 2009);
insert into cars (id, model, maker, year) values (998, 'Park Avenue', 'Buick', 1998);
insert into cars (id, model, maker, year) values (999, 'Sierra 2500', 'GMC', 2005);
insert into cars (id, model, maker, year) values (1000, 'T100', 'Toyota', 1993);
